---

- name: import secret variable file
  include_vars: "fake_ssh.yml"
  no_log: true

- name: copy deployment private key
  copy:
    content: "{{private_key_content}}"
    dest: "/home/sashreek/.ssh/id_rsa"
    owner: sashreek
    group: sashreek
    mode: 0600
  no_log: true
