---
- name: Make Vim directory
  become: false
  file:
    path: "~/.vim"
    state: directory

- name: Make Vim bundle directory
  become: false
  file:
    path: "~/.vim/bundle"
    state: directory

- name: Clone vundle
  become: false
  git:
    repo: "git://github.com/VundleVim/Vundle.vim.git"
    dest: "~/.vim/bundle/Vundle.vim"
    accept_hostkey: "no"
    version: "master"
    
- name: Ensure system-wide vim config only so users can set own preferences 
  template: 
    src: vimrc.j2 
    dest: "~/.vim/vimrc"
    owner: "{{owner}}" 
    group: "{{group}}"
    mode: 644
  become: false

- name: Ensure Vim Plugin directory exists
  file: path="~/.vim" state=directory owner="{{owner}}" group="{{group}}"
  become: yes

- name: Install Vim plugins
  command: "vim +PluginInstall +qall"